language: java

jdk:
  - openjdk11

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.m2/repository/"

install: "/bin/true"

jobs:
  include:
    - stage: test
      name: "junit gradle plugin"
      script: "./gradlew test"
    - stage: test
      name: "kotlintest gradle plugin"
      script: "./gradlew kotlintest"
    - stage: deploy
      script: "./snapshot_deploy.sh"
