site_name: Kotest Test Framework

# Meta tags (placed in header)
site_description: Kotest test framework for Kotlin.
site_author: Kotest organization
site_url: https://kotest.io

markdown_extensions:
   - admonition
   - attr_list
   -  pymdownx.highlight:
         use_pygments: true

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2017 Kotest Team'

# Repository (add link to repository on each page)
repo_name: Kotest
repo_url: https://github.com/kotest/kotest

theme:
   icon:
      repo: fontawesome/brands/github
   name: material
   palette:
      primary: indigo
      accent: deep orange
   logo: 'images/logo.png'
   features:
      - search.highlight
      - tabs
   font:
      text: Heebo

google_analytics:
   - UA-177425497-1
   - auto

plugins:
   - search

extra:
   social:
      -  icon: fontawesome/brands/slack
         link: https://kotlinlang.slack.com/?redir=%2Farchives%2FCT0G9SD7Z
      -  icon: fontawesome/brands/github
         link: https://github.com/kotest/kotest


nav:
   -  Overview:
         -  "Welcome": "index.md"
         - "quick_start.md"
         - "changelog.md"
   -  Framework:
         - "styles.md"
         - "extensions.md"
         - "listeners.md"
         - "data_driven_testing.md"
         - "test_ordering.md"
         - "spec_ordering.md"
         - "conditional_evaluation.md"
         - "isolation_mode.md"
         - "timeout.md"
         - "tags.md"
         - "project_config.md"
         - "nondeterministic_testing.md"
         - "test_factories.md"
         - "mocks.md"
         - "mpp.md"
         - "plugins.md"
   -  "Assertions":
         - "assertions.md"
         - "matchers.md"
         - "inspectors.md"
   -  "Property Testing":
         -  "Introduction": property_testing.md
         -  "Generators": property_generators.md
         -  "Generator Operations": property_ops.md
   -  Issues: "https://github.com/kotest/kotest/issues"
   -  More:
         - "blogs.md"
         - "third_party_integrations.md"
