name: build-master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - '*.md'
      branches:
         - master

jobs:
   build:
      strategy:
         matrix:
            os: [macOS-latest, windows-latest, ubuntu-latest]

      runs-on: ${{matrix.os}}

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: Run ubuntu tests
            if: matrix.os == 'ubuntu-latest'
            run: ./gradlew check

         -  name: Run windows tests
            if: matrix.os == 'windows-latest'
            run: ./gradlew nativeTest

         -  name: Run macOS tests
            if: matrix.os == 'macOS-latest'
            run: ./gradlew nativeTest

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

   deploy-linux-and-common:
      needs: build
      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: deploy to sonatype snapshots
            run: ./gradlew publish
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

   deploy-mac:
      needs: build
      runs-on: macOS-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: deploy to sonatype snapshots
            run: ./gradlew publishNativePublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

   deploy-windows:
      needs: build
      runs-on: windows-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: deploy to sonatype snapshots
            run: ./gradlew publishNativePublicationToDeployRepository
            env:
               OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
