name: build-master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - '*.md'
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            product: [ "IC-211", "IC-212", "IC-213", "IC-221", "IC-222", "IC-223", "IC-231", "IC-232", "IC-233" ]
            include:
               -  product: "IC-211"
                  java: "11"
                  distribution: "adopt"
               -  product: "IC-212"
                  java: "11"
                  distribution: "adopt"
               -  product: "IC-213"
                  java: "11"
                  distribution: "adopt"
               -  product: "IC-221"
                  java: "11"
                  distribution: "adopt"
               -  product: "IC-222"
                  java: "11"
                  distribution: "adopt"
               -  product: "IC-223"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-231"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-232"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-233"
                  java: "17"
                  distribution: "temurin"
         max-parallel: 10
         fail-fast: false

      steps:
         -  uses: actions/checkout@v4
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v4
            with:
               java-version: ${{ matrix.java }}
               distribution: ${{ matrix.distribution }}

         -  name: Run tests
            run: ./gradlew check
            env:
               PRODUCT_NAME: ${{ matrix.product }}

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
