name: release

on:
   workflow_dispatch:

jobs:
   release:

      strategy:
         matrix:
            product: [ "IC-193", "IC-201", "IC-202", "IC-203", "IC-211", "IC-213" ]
         max-parallel: 1

      runs-on: ubuntu-latest

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v1
            with:
               java-version: '11'
               java-package: jdk
               architecture: x64

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ matrix.product }}
               JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
