name: release-intellij-plugin

on:
   workflow_dispatch:

jobs:
   release:

      strategy:
         matrix:
            product: [ "IC-251", "IC-252", "IC-253", "IC-261" ]
         max-parallel: 1

      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v6
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v5
            with:
               java-version: "21"
               distribution: "temurin"

         -  name: Override Kotlin version for IC-261
            if: matrix.product == 'IC-261'
            run: sed -i 's/^kotlin = .*/kotlin = "2.3.10"/' gradle/libs.versions.toml

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ matrix.product }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
