name: release_single

on:
   workflow_dispatch:
      inputs:
         sdk:
            type: string
            description: "sdk folder eg IC-222"
            required: true

jobs:
   release:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v3
            if: matrix.product != 'IC-223' && matrix.product != 'IC-231'
            with:
               distribution: 'adopt'
               java-version: '11'

         -  uses: actions/setup-java@v3
            if: matrix.product == 'IC-223' || matrix.product == 'IC-231'
            with:
               distribution: 'temurin'
               java-version: '17'

         -  uses: actions/setup-java@v3
            with:
               distribution: 'adopt'
               java-version: '17'

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ github.event.inputs.sdk }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
