name: release_single

on:
   workflow_dispatch:
      inputs:
         sdk:
            type: string
            description: "sdk folder eg IC-222"
            required: true
         java:
            type: string
            description: "11 or 17"
            required: true
         distribution:
            type: string
            description: "adopt or temurin"
            required: true

jobs:
   release:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v4
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v4
            with:
               java-version: ${{ inputs.java }}
               distribution: ${{ inputs.distribution }}

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ github.event.inputs.sdk }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
