name: release

on:
   workflow_dispatch:

jobs:
   release:

      strategy:
         matrix:
            product: [ "IC-223", "IC-231", "IC-232", "IC-233", "IC-241" ]
            include:
               -  product: "IC-223"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-231"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-232"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-233"
                  java: "17"
                  distribution: "temurin"
               -  product: "IC-241"
                  java: "17"
                  distribution: "temurin"
         max-parallel: 1

      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v4
            with:
               fetch-depth: 0

         -  uses: actions/setup-java@v4
            with:
               java-version: ${{ matrix.java }}
               distribution: ${{ matrix.distribution }}

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
            env:
               PRODUCT_NAME: ${{ matrix.product }}

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
